# Generated by Django 4.1 on 2024-03-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roger_preprep_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
