# Generated by Django 4.1 on 2024-03-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_post_op_alter_roger_preprep_line_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_op',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='post_op',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='todo_obj',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='todo_phase',
            old_name='update',
            new_name='updated',
        ),
    ]
