# Generated by Django 4.1 on 2024-03-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_todo_obj_todo_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_obj',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='todo_obj',
            name='update',
            field=models.DateTimeField(),
        ),
    ]
