# Generated by Django 4.1 on 2024-03-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_alter_post_op_options_rename_update_post_op_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_op',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
