# Generated by Django 4.1 on 2024-03-25 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0008_alter_post_op_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_op',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
