# Generated by Django 4.1 on 2024-03-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_post_op_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_reply',
            old_name='op',
            new_name='original',
        ),
    ]
