# Generated by Django 4.1 on 2024-04-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_rename_op_post_reply_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wf_city',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
